btba_chat-add:
    path: /add
    controller: Btba\ChatBundle\Controller\ChatController::add
    options:
        expose: true

btba_chat-test:
    path: /test
    controller: 'Btba\ChatBundle\Controller\ChatController::test'