btba_chat-add:
    path: /add
    controller: App\Controller\ChatController::add
    options:
        expose: true

btba_chat-test:
    path: /test
    controller: 'btba\ChatBundle\Controller\ChatController::test'