services:
    _defaults:
        bind:
            $message_class: '%btba_chat.message_class%'
        public: true

    btba_chat.type:
        class: Btba\ChatBundle\Form\ChatMessageType
        tags:
            - {name: form.type }
        arguments:
            $trans: "@translator"

    btba_chat.controller:
        class: Btba\ChatBundle\Controller\ChatController
        tags: ['controller.service_arguments']

    Btba\ChatBundle\Controller\ChatController:
        alias: btba_chat.controller