

services:

    _defaults:
        autowire: true 
        bind:
            $message_class: '%btba_chat.message_class%'

    chat.type:
        class: btba\ChatBundle\Form\ChatMessageType
        tags:
            - {name: form.type }
        arguments:
            $trans: "@translator"